// user info
export const USER_IS_AUTHENTICATING = 'USER_IS_AUTHENTICATING';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_STATE_OK = 'USER_STATE_OK';
export const USER_STATE_MESSAGE = 'USER_STATE_MESSAGE';

// journal list
export const JOURNAL_LIST_IS_POSTING = 'JOURNAL_LIST_IS_POSTING';
export const JOURNAL_LIST_IS_LOADING = 'JOURNAL_LIST_IS_LOADING';
export const JOURNAL_LIST_GET_SUCCESS = 'JOURNAL_LIST_GET_SUCCESS';
export const JOURNAL_LIST_STATUS = 'JOURNAL_LIST_STATUS';
export const ADD_TO_JOURNAL_LIST = 'ADD_TO_JOURNAL_LIST';
export const EDIT_JOURNAL_LIST = 'EDIT_JOURNAL_LIST';

// user settings
export const USER_SETTINGS_IS_POSTING = 'USER_SETTINGS_IS_POSTING';
export const USER_SETTINGS_IS_LOADING = 'USER_SETTINGS_IS_LOADING';
export const USER_SETTINGS_OK = 'USER_SETTINGS_OK';
export const USER_SETTINGS_MESSAGE = 'USER_SETTINGS_MESSAGE';

//settings
export const SETTINGS_GET_SUCCESS = 'SETTINGS_GET_SUCCESS';
export const TOGGLE_TEMP_UNIT = 'TOGGLE_TEMP_UNIT';

// profile
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS';

// weather stamp
export const WEATHER_STAMP_IS_LOADING = 'WEATHER_STAMP_IS_LOADING';
export const WEATHER_STAMP_ERROR = 'WEATHER_STAMP_FETCH_ERROR';
export const WEATHER_OBJECT_GET_SUCCESS = 'WEATHER_OBJECT_GET_SUCCESS';
export const MAIN_GET_SUCCESS = 'MAIN_GET_SUCCESS';
export const WEATHER_GET_SUCCESS = 'WEATHER_GET_SUCCESS';

// journal entry
export const WEATHER_DATA_IS_POSTING = 'WEATHER_DATA_IS_POSTING';
export const WEATHER_DATA_ERROR = 'WEATHER_DATA_ERROR';
export const WEATHER_DATA_POST_SUCCESS = 'WEATHER_DATA_POST_SUCCESS';
