// journal entry list
export const ADD_TO_JOURNAL_LIST = 'ADD_TO_JOURNAL_LIST';
export const EDIT_JOURNAL_LIST = 'EDIT_JOURNAL_LIST';

// weather stamp
export const WEATHER_STAMP_IS_LOADING = 'WEATHER_STAMP_IS_LOADING';
export const WEATHER_STAMP_ERROR = 'WEATHER_STAMP_FETCH_ERROR';
export const WEATHER_OBJECT_SUCCESS = 'WEATHER_OBJECT_SUCCESS';
export const MAIN_SUCCESS = 'MAIN_SUCCESS';
export const WEATHER_SUCCESS = 'WEATHER_SUCCESS';

// journal entry
export const JOURNAL_MODE = 'JOURNAL_MODE';

export const WEATHER_DATA_IS_POSTING = 'WEATHER_DATA_IS_POSTING';
export const WEATHER_DATA_ERROR = 'WEATHER_DATA_ERROR';
export const WEATHER_DATA_POST_SUCCESS = 'WEATHER_DATA_POST_SUCCESS';

// export const SET_API_CALL_TYPE = 'SET_API_CALL_TYPE';
// export const SET_API_CALL_PARAMS = 'SET_API_CALL_PARAMS';
// export const SET_HTTP_STATUS_CODE = 'SET_HTTP_STATUS_CODE';
// export const SET_MESSAGE = 'SET_MESSAGE';
