// journal entry list actions.js
const ADD_TO_JOURNAL_ENTRY_LIST = 'ADD_TO_JOURNAL_ENTRY_LIST';
const EDIT_JOURNAL_ENTRY_LIST = 'EDIT_JOURNAL_ENTRY_LIST';
// weather stamp actions.js
const SET_WEATHER_OBJECT = 'SET_WEATHER_OBJECT';
const SET_MAIN = 'SET_MAIN';
const SET_WEATHER = 'SET_WEATHER';
// journal entry actions.js
const SET_API_CALL_TYPE = 'SET_API_CALL_TYPE';
const SET_API_CALL_PARAMS = 'SET_API_CALL_PARAMS';
const SET_HTTP_STATUS_CODE = 'SET_HTTP_STATUS_CODE';
const SET_MESSAGE = 'SET_MESSAGE';

export {
  ADD_TO_JOURNAL_ENTRY_LIST,
  EDIT_JOURNAL_ENTRY_LIST,
  SET_WEATHER_OBJECT,
  SET_MAIN,
  SET_WEATHER,
  SET_API_CALL_TYPE,
  SET_API_CALL_PARAMS,
  SET_HTTP_STATUS_CODE,
  SET_MESSAGE,
};
